import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Or whichever font you use
import "./globals.css";
import Sidebar from "../components/Sidebar"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white `}>
       
        <Sidebar />

        <main className="ml-[84px] min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}